name: flutter_xianyu
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3             # ios 风格的icon
  flutter_easyrefresh: ^2.1.8        # 下拉刷新
  json_annotation: ^2.0.0            # json 转 model 
  flutter_staggered_grid_view: ^0.3.4 # 瀑布流
  cached_network_image: ^2.5.0    # 图片缓存框架
  # flutter_swiper: ^1.1.6  #滚动 banner
  scrollable_positioned_list: ^0.1.10  # 滚动指定位置的 listView
  provider: ^4.3.3  ## provider 
  # flutter_sticky_header: ^0.5.0 # header
  lottie: ^0.7.0              # lottie 动画类
  video_player: ^1.0.1       # 视频播放控件
  qrscan: ^0.2.21   ## 扫一扫控件

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner: ^1.0.0

  json_serializable: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    ## images

    # - images/image_demo.jpg
    # - images/ic_notificate.png
    # - images/ic_setting.png
    # - images/ic_navibar_setting.png
    # - images/refresh_loading.png 
    # - images/refresh_normal.png
    # - images/refresh_pulling.png
    - images/
    ## jsons 
    - assets/
    - xianyu_json/

    # - assets/fun1.json 
    # - assets/fun2.json 
    # - assets/fun3.json 
    # - assets/fun4.json 
    # - assets/fun5.json 
    # - assets/fun6.json 
    # - assets/fun7.json 
    # - assets/fun8.json 

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
